require 'calculator/version'
require 'calculator/base'
require 'calculator/disciplines/sprint'
require 'calculator/disciplines/run'
require 'calculator/disciplines/long_jump'
require 'calculator/disciplines/medicine_ball'
